### ISSUE TITLE
Every Edge removing BATCH File fails and crashes instantly

### ISSUE THREAD

**Issue by ghost** [mrhaydendp/RemoveEdge#6]
I have tried all the Edge removal GitHub projects and all of them give an error and crash.

**Comment by mrhaydendp** [comment]
How did you run the file? The recommended way is to open Windows Terminal/Powershell with Admin privileges (by pressing Windows Key + X) and pasting in the following command:
```
irm "https://github.com/mrhaydendp/RemoveEdge/raw/main/RemoveEdge.ps1" | iex
```

**Comment by mrhaydendp** [comment]
Here's a gif showing how to run it:
![RemoveEdge Tutorial](https://github.com/user-attachments/assets/9e948715-6fa4-4518-8dd5-cb6b346c44f1)
